modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="repo_love_potion"
version="0.6.9"
displayName="REPO Love Potion"
displayURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
credits="Made for lizzy."
authors="Roland"

[[dependencies.repo_love_potion]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.repo_love_potion]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.repo_love_potion]]
    modId="appleskin"
    type="required"
    versionRange="[3.0.5,3.1.7)"
    ordering="NONE"
    side="BOTH"
[[dependencies.repo_love_potion]]
    modId="create"
    type="required"
    versionRange="[6.0.4,6.1.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.repo_love_potion]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.2.7,1.4.9)"
    ordering="NONE"
    side="BOTH"
[[dependencies.repo_love_potion]]
    modId="polymorph"
    type="required"
    versionRange="[1.0.8,1.2.3)"
    ordering="NONE"
    side="BOTH"